# Step 1 : Load Data

In [13]:
import pandas as pd

performance_metrics_path = '/Users/zxgan/FYP_Kubernetes/Dataset/kubernetes_performance_metrics_dataset.csv'
resource_allocation_path = '/Users/zxgan/FYP_Kubernetes/Dataset/kubernetes_resource_allocation_dataset.csv'

performance_metrics = pd.read_csv(performance_metrics_path)
resource_allocation = pd.read_csv(resource_allocation_path)

merged_data = pd.merge(performance_metrics, resource_allocation, on=['pod_name'], how='inner')

merged_data.to_csv('/Users/zxgan/FYP_Kubernetes/Dataset/merged_kubernetes_dataset.csv', index=False)

In [14]:
merged_data.head(20)

,timestamp,pod_name,namespace_x,cpu_allocation_efficiency,memory_allocation_efficiency,disk_io,network_latency,node_temperature,node_cpu_usage,node_memory_usage,...,memory_limit,cpu_usage,memory_usage,node_name,pod_status,restart_count,uptime_seconds,deployment_strategy,scaling_policy,network_bandwidth_usage
0,01/01/2023 00:00,pod_0,dev,0.038162,0.949259,9.993579,13.722542,77.619073,93.177619,37.900532,...,5134.413852,3.345496,2135.310365,node_12,Failed,0,76536,RollingUpdate,Manual,459.015733
1,01/01/2023 00:00,pod_1,default,0.500763,0.048543,935.792442,55.493953,84.182245,61.442289,5.208161,...,3698.349366,2.758188,7442.200271,node_18,Unknown,2,97849,RollingUpdate,Manual,507.770808
2,01/01/2023 00:00,pod_2,kube-system,0.746726,0.447345,328.352359,173.910016,21.295244,55.819311,18.335802,...,7418.271122,1.319703,5142.897754,node_7,Failed,2,47370,RollingUpdate,Manual,527.702531
3,01/01/2023 00:00,pod_3,default,0.526692,0.870251,778.297708,67.395729,85.028829,78.968463,94.619689,...,3628.480705,3.752312,2952.449331,node_20,Failed,6,5685,Recreate,Auto,473.530315
4,01/01/2023 00:00,pod_4,prod,0.425342,0.885459,711.181295,91.724730,29.157695,52.718141,70.770594,...,5091.497752,0.874224,3382.299355,node_38,Unknown,3,4502,Recreate,Auto,973.928080
5,01/01/2023 00:00,pod_5,prod,0.776035,0.978772,971.800922,31.386060,88.422454,61.193238,70.048466,...,5590.519940,2.901598,5052.061409,node_28,Succeeded,4,19749,Recreate,Manual,888.567798
6,01/01/2023 00:00,pod_6,dev,0.789514,0.977272,883.049263,121.004965,34.083814,38.796297,15.081287,...,1878.649322,2.957520,6301.942618,node_26,Running,8,87990,RollingUpdate,Auto,930.742111
7,01/01/2023 00:00,pod_7,prod,0.963772,0.429530,965.425844,129.968582,63.203020,24.045878,56.860129,...,7240.498095,1.310631,1898.337488,node_1,Failed,7,10467,RollingUpdate,Auto,349.460488
8,01/01/2023 00:00,pod_8,dev,0.022299,0.467883,426.580340,103.565620,23.767933,23.277313,60.798199,...,5326.313573,0.614677,4393.776140,node_19,Failed,7,84398,Recreate,Manual,144.289755
9,01/01/2023 00:00,pod_9,default,0.780019,0.778220,788.328514,1.630378,21.578828,48.863855,64.858434,...,1735.092407,2.149355,5602.480931,node_47,Unknown,3,47676,Recreate,Auto,222.946789
10,01/01/2023 00:00,pod_10,dev,0.172274,0.753025,907.132516,67.974656,32.754965,25.256423,43.372460,...,1563.443511,1.729358,4519.302318,node_6,Running,9,40864,Recreate,Manual,723.006449
11,01/01/2023 00:00,pod_11,default,0.747688,0.803754,990.425042,30.672308,85.923898,17.356885,37.106336,...,6373.698240,3.981147,1864.357619,node_26,Pending,3,77896,RollingUpdate,Auto,431.260453
12,01/01/2023 00:00,pod_12,dev,0.812515,0.134778,852.119262,122.286390,41.916295,12.369194,57.255298,...,5808.180740,3.318026,7075.217691,node_15,Running,1,99826,Recreate,Manual,456.007859
13,01/01/2023 00:00,pod_13,dev,0.354114,0.992757,964.415904,156.662830,89.437962,37.970451,49.145359,...,2728.581320,2.137358,2616.661723,node_34,Unknown,6,45555,RollingUpdate,Manual,885.464617
14,01/01/2023 00:00,pod_14,default,0.342024,0.764794,381.124295,97.494803,92.659249,43.500499,79.961734,...,6769.349018,0.702459,5198.034511,node_11,Failed,7,48075,Recreate,Auto,791.768443
15,01/01/2023 00:00,pod_15,prod,0.511985,0.280418,154.773332,192.512880,51.634929,80.559119,38.426094,...,4281.283997,2.124689,7476.139981,node_16,Running,8,6108,RollingUpdate,Manual,98.434416
16,01/01/2023 00:00,pod_16,dev,0.045943,0.638657,744.814877,85.621489,34.424282,11.947994,41.726898,...,7932.007514,2.193281,6001.018146,node_9,Pending,0,57711,RollingUpdate,Auto,542.232833
17,01/01/2023 00:00,pod_17,dev,0.289359,0.422795,33.566967,181.721634,88.325587,16.661476,92.215828,...,3955.681046,1.008706,2782.899896,node_26,Running,1,56629,Recreate,Manual,667.260072
18,01/01/2023 00:00,pod_18,default,0.481552,0.425022,993.145288,117.665845,96.482176,43.831325,13.878301,...,2946.904541,2.143988,1079.392039,node_46,Unknown,7,50319,RollingUpdate,Auto,518.864885
19,01/01/2023 00:00,pod_19,prod,0.416678,0.758125,189.605030,88.424877,26.705727,24.821938,88.714623,...,7714.762503,3.912662,3235.209211,node_12,Succeeded,2,68064,RollingUpdate,Manual,549.094527

# Step 2 : Data Understanding

In [15]:
merged_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 28 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   timestamp                     15000 non-null  object
 1   pod_name                      15000 non-null  object
 2   namespace_x                   15000 non-null  object
 3   cpu_allocation_efficiency     15000 non-null  float64
 4   memory_allocation_efficiency  15000 non-null  float64
 5   disk_io                       15000 non-null  float64
 6   network_latency               15000 non-null  float64
 7   node_temperature              15000 non-null  float64
 8   node_cpu_usage                15000 non-null  float64
 9   node_memory_usage             15000 non-null  float64
 10  event_type                    15000 non-null  object
 11  event_message                 15000 non-null  object
 12  scaling_event                 15000 non-null  bool
 13  pod_lifetime_seconds          15000 non-null  int64
 14  namespace_y                   15000 non-null  object
 15  cpu_request                   15000 non-null  float64
 16  cpu_limit                     15000 non-null  float64
 17  memory_request                15000 non-null  float64
 18  memory_limit                  15000 non-null  float64
 19  cpu_usage                     15000 non-null  float64
 20  memory_usage                  15000 non-null  float64
 21  node_name                     15000 non-null  object
 22  pod_status                    15000 non-null  object
 23  restart_count                 15000 non-null  int64
 24  uptime_seconds                15000 non-null  int64
 25  deployment_strategy           15000 non-null  object
 26  scaling_policy                15000 non-null  object
 27  network_bandwidth_usage       15000 non-null  float64
dtypes: bool(1), float64(14), int64(3), object(10)
memory usage: 3.1+ MB

In [16]:
merged_data.nunique()

timestamp                         250
pod_name                        15000
namespace_x                         4
cpu_allocation_efficiency       15000
memory_allocation_efficiency    15000
disk_io                         15000
network_latency                 15000
node_temperature                15000
node_cpu_usage                  15000
node_memory_usage               15000
event_type                          3
event_message                       5
scaling_event                       2
pod_lifetime_seconds            14431
namespace_y                         4
cpu_request                     15000
cpu_limit                       15000
memory_request                  15000
memory_limit                    15000
cpu_usage                       15000
memory_usage                    15000
node_name                          50
pod_status                          5
restart_count                      10
uptime_seconds                  13940
deployment_strategy                 2
scaling_policy                      2
network_bandwidth_usage         15000
dtype: int64

In [17]:
#check duplicated rows
merged_data.duplicated().sum()

0

In [18]:
#check missing values
missing_value=merged_data.isnull().sum()

print(missing_value)

timestamp                       0
pod_name                        0
namespace_x                     0
cpu_allocation_efficiency       0
memory_allocation_efficiency    0
disk_io                         0
network_latency                 0
node_temperature                0
node_cpu_usage                  0
node_memory_usage               0
event_type                      0
event_message                   0
scaling_event                   0
pod_lifetime_seconds            0
namespace_y                     0
cpu_request                     0
cpu_limit                       0
memory_request                  0
memory_limit                    0
cpu_usage                       0
memory_usage                    0
node_name                       0
pod_status                      0
restart_count                   0
uptime_seconds                  0
deployment_strategy             0
scaling_policy                  0
network_bandwidth_usage         0
dtype: int64

# Step 3 : Data Cleaning

In [19]:
# convert timestamp to standard datetime format

from datetime import datetime
merged_data['timestamp'] = pd.to_datetime(merged_data['timestamp'], errors='coerce', format='%d/%m/%Y %H:%M')

In [20]:
# perform scaling on the dataset
from sklearn.preprocessing import MinMaxScaler, LabelEncoder

scaling_columns = [
    "disk_io", "network_latency", "node_temperature", "node_cpu_usage", 
    "node_memory_usage", "cpu_request", "cpu_limit", "memory_request", 
    "memory_limit", "cpu_usage", "memory_usage", "network_bandwidth_usage"
]

scaler = MinMaxScaler()
merged_data[scaling_columns] = scaler.fit_transform(merged_data[scaling_columns])

merged_data.head(20)

,timestamp,pod_name,namespace_x,cpu_allocation_efficiency,memory_allocation_efficiency,disk_io,network_latency,node_temperature,node_cpu_usage,node_memory_usage,...,memory_limit,cpu_usage,memory_usage,node_name,pod_status,restart_count,uptime_seconds,deployment_strategy,scaling_policy,network_bandwidth_usage
0,2023-01-01,pod_0,dev,0.038162,0.949259,0.009904,0.068610,0.720406,0.931793,0.378946,...,0.614720,0.836367,0.260661,node_12,Failed,0,76536,RollingUpdate,Manual,0.459041
1,2023-01-01,pod_1,default,0.500763,0.048543,0.935862,0.277469,0.802465,0.614357,0.051991,...,0.433756,0.689518,0.908485,node_18,Unknown,2,97849,RollingUpdate,Manual,0.507800
2,2023-01-01,pod_2,kube-system,0.746726,0.447345,0.328318,0.869555,0.016188,0.558113,0.183280,...,0.902517,0.329844,0.627804,node_7,Failed,2,47370,RollingUpdate,Manual,0.527733
3,2023-01-01,pod_3,default,0.526692,0.870251,0.778340,0.336979,0.813050,0.789665,0.946192,...,0.424952,0.938086,0.360411,node_20,Failed,6,5685,Recreate,Auto,0.473557
4,2023-01-01,pod_4,prod,0.425342,0.885459,0.711212,0.458625,0.114493,0.527093,0.707678,...,0.609312,0.218458,0.412884,node_38,Unknown,3,4502,Recreate,Auto,0.973990
5,2023-01-01,pod_5,prod,0.776035,0.978772,0.971876,0.156929,0.855481,0.611866,0.700456,...,0.672196,0.725376,0.616716,node_28,Succeeded,4,19749,Recreate,Manual,0.888623
6,2023-01-01,pod_6,dev,0.789514,0.977272,0.883109,0.605027,0.176084,0.387838,0.150732,...,0.204449,0.739359,0.769292,node_26,Running,8,87990,RollingUpdate,Auto,0.930801
7,2023-01-01,pod_7,prod,0.963772,0.429530,0.965500,0.649846,0.540162,0.240296,0.568560,...,0.880116,0.327576,0.231733,node_1,Failed,7,10467,RollingUpdate,Auto,0.349478
8,2023-01-01,pod_8,dev,0.022299,0.467883,0.426562,0.517830,0.047104,0.232608,0.607945,...,0.638902,0.153562,0.536357,node_19,Failed,7,84398,Recreate,Manual,0.144293
9,2023-01-01,pod_9,default,0.780019,0.778220,0.788372,0.008149,0.019734,0.488540,0.648551,...,0.186359,0.537288,0.683907,node_47,Unknown,3,47676,Recreate,Auto,0.222956
10,2023-01-01,pod_10,dev,0.172274,0.753025,0.907197,0.339873,0.159469,0.252404,0.433671,...,0.164729,0.432273,0.551680,node_6,Running,9,40864,Recreate,Manual,0.723050
11,2023-01-01,pod_11,default,0.747688,0.803754,0.990504,0.153360,0.824241,0.173388,0.371003,...,0.770887,0.995303,0.227585,node_26,Pending,3,77896,RollingUpdate,Auto,0.431284
12,2023-01-01,pod_12,dev,0.812515,0.134778,0.852174,0.611434,0.274014,0.123498,0.572512,...,0.699624,0.829499,0.863687,node_15,Running,1,99826,Recreate,Manual,0.456033
13,2023-01-01,pod_13,dev,0.354114,0.992757,0.964490,0.783318,0.868177,0.379578,0.491405,...,0.311552,0.534288,0.319421,node_34,Unknown,6,45555,RollingUpdate,Manual,0.885520
14,2023-01-01,pod_14,default,0.342024,0.764794,0.381099,0.487475,0.908453,0.434893,0.799599,...,0.820744,0.175510,0.634535,node_11,Failed,7,48075,Recreate,Auto,0.791817
15,2023-01-01,pod_15,prod,0.511985,0.280418,0.154709,0.962570,0.395526,0.805575,0.384202,...,0.507214,0.531120,0.912629,node_16,Running,8,6108,RollingUpdate,Manual,0.098435
16,2023-01-01,pod_16,dev,0.045943,0.638657,0.744851,0.428108,0.180341,0.119285,0.417214,...,0.967255,0.548271,0.732557,node_9,Pending,0,57711,RollingUpdate,Auto,0.542264
17,2023-01-01,pod_17,dev,0.289359,0.422795,0.033482,0.908613,0.854269,0.166432,0.922151,...,0.466184,0.252084,0.339714,node_26,Running,1,56629,Recreate,Manual,0.667300
18,2023-01-01,pod_18,default,0.481552,0.425022,0.993224,0.588332,0.956251,0.438202,0.138701,...,0.339064,0.535946,0.131762,node_46,Unknown,7,50319,RollingUpdate,Auto,0.518894
19,2023-01-01,pod_19,prod,0.416678,0.758125,0.189547,0.442125,0.083836,0.248058,0.887136,...,0.939879,0.978179,0.394928,node_12,Succeeded,2,68064,RollingUpdate,Manual,0.549126

In [21]:
# perform one-hot encoding on the dataset
categories = {
    "pod_status": ["Running", "Pending", "Succeeded", "Failed", "Unknown"],
}

# One-hot encode columns with pre-specified categories
for column, unique_values in categories.items():
    for value in unique_values:
        col_name = f"{column}_{value}"
        if col_name not in merged_data.columns:
            merged_data[col_name] = (merged_data[column] == value).astype(int) if column in merged_data else 0


merged_data = merged_data.drop(columns=categories.keys(), errors='ignore')

merged_data.head(20)

,timestamp,pod_name,namespace_x,cpu_allocation_efficiency,memory_allocation_efficiency,disk_io,network_latency,node_temperature,node_cpu_usage,node_memory_usage,...,restart_count,uptime_seconds,deployment_strategy,scaling_policy,network_bandwidth_usage,pod_status_Running,pod_status_Pending,pod_status_Succeeded,pod_status_Failed,pod_status_Unknown
0,2023-01-01,pod_0,dev,0.038162,0.949259,0.009904,0.068610,0.720406,0.931793,0.378946,...,0,76536,RollingUpdate,Manual,0.459041,0,0,0,1,0
1,2023-01-01,pod_1,default,0.500763,0.048543,0.935862,0.277469,0.802465,0.614357,0.051991,...,2,97849,RollingUpdate,Manual,0.507800,0,0,0,0,1
2,2023-01-01,pod_2,kube-system,0.746726,0.447345,0.328318,0.869555,0.016188,0.558113,0.183280,...,2,47370,RollingUpdate,Manual,0.527733,0,0,0,1,0
3,2023-01-01,pod_3,default,0.526692,0.870251,0.778340,0.336979,0.813050,0.789665,0.946192,...,6,5685,Recreate,Auto,0.473557,0,0,0,1,0
4,2023-01-01,pod_4,prod,0.425342,0.885459,0.711212,0.458625,0.114493,0.527093,0.707678,...,3,4502,Recreate,Auto,0.973990,0,0,0,0,1
5,2023-01-01,pod_5,prod,0.776035,0.978772,0.971876,0.156929,0.855481,0.611866,0.700456,...,4,19749,Recreate,Manual,0.888623,0,0,1,0,0
6,2023-01-01,pod_6,dev,0.789514,0.977272,0.883109,0.605027,0.176084,0.387838,0.150732,...,8,87990,RollingUpdate,Auto,0.930801,1,0,0,0,0
7,2023-01-01,pod_7,prod,0.963772,0.429530,0.965500,0.649846,0.540162,0.240296,0.568560,...,7,10467,RollingUpdate,Auto,0.349478,0,0,0,1,0
8,2023-01-01,pod_8,dev,0.022299,0.467883,0.426562,0.517830,0.047104,0.232608,0.607945,...,7,84398,Recreate,Manual,0.144293,0,0,0,1,0
9,2023-01-01,pod_9,default,0.780019,0.778220,0.788372,0.008149,0.019734,0.488540,0.648551,...,3,47676,Recreate,Auto,0.222956,0,0,0,0,1
10,2023-01-01,pod_10,dev,0.172274,0.753025,0.907197,0.339873,0.159469,0.252404,0.433671,...,9,40864,Recreate,Manual,0.723050,1,0,0,0,0
11,2023-01-01,pod_11,default,0.747688,0.803754,0.990504,0.153360,0.824241,0.173388,0.371003,...,3,77896,RollingUpdate,Auto,0.431284,0,1,0,0,0
12,2023-01-01,pod_12,dev,0.812515,0.134778,0.852174,0.611434,0.274014,0.123498,0.572512,...,1,99826,Recreate,Manual,0.456033,1,0,0,0,0
13,2023-01-01,pod_13,dev,0.354114,0.992757,0.964490,0.783318,0.868177,0.379578,0.491405,...,6,45555,RollingUpdate,Manual,0.885520,0,0,0,0,1
14,2023-01-01,pod_14,default,0.342024,0.764794,0.381099,0.487475,0.908453,0.434893,0.799599,...,7,48075,Recreate,Auto,0.791817,0,0,0,1,0
15,2023-01-01,pod_15,prod,0.511985,0.280418,0.154709,0.962570,0.395526,0.805575,0.384202,...,8,6108,RollingUpdate,Manual,0.098435,1,0,0,0,0
16,2023-01-01,pod_16,dev,0.045943,0.638657,0.744851,0.428108,0.180341,0.119285,0.417214,...,0,57711,RollingUpdate,Auto,0.542264,0,1,0,0,0
17,2023-01-01,pod_17,dev,0.289359,0.422795,0.033482,0.908613,0.854269,0.166432,0.922151,...,1,56629,Recreate,Manual,0.667300,1,0,0,0,0
18,2023-01-01,pod_18,default,0.481552,0.425022,0.993224,0.588332,0.956251,0.438202,0.138701,...,7,50319,RollingUpdate,Auto,0.518894,0,0,0,0,1
19,2023-01-01,pod_19,prod,0.416678,0.758125,0.189547,0.442125,0.083836,0.248058,0.887136,...,2,68064,RollingUpdate,Manual,0.549126,0,0,1,0,0

In [22]:
#drop the pod_name, namespace_x, namespace_y, event_type, event_message, scalling_event, pod_lifetime_seconds, restart_count, uptime_seconds, deployment_strategy, scaling_policy, 

cleaned_data = merged_data.drop(columns=['pod_name', 'namespace_x', 'namespace_y', 'event_type', 'event_message', 'scaling_event', 'pod_lifetime_seconds', 'restart_count', 'uptime_seconds', 'deployment_strategy', 'scaling_policy'], errors='ignore')

cleaned_data.head(20)

,timestamp,cpu_allocation_efficiency,memory_allocation_efficiency,disk_io,network_latency,node_temperature,node_cpu_usage,node_memory_usage,cpu_request,cpu_limit,...,memory_limit,cpu_usage,memory_usage,node_name,network_bandwidth_usage,pod_status_Running,pod_status_Pending,pod_status_Succeeded,pod_status_Failed,pod_status_Unknown
0,2023-01-01,0.038162,0.949259,0.009904,0.068610,0.720406,0.931793,0.378946,0.773474,0.908433,...,0.614720,0.836367,0.260661,node_12,0.459041,0,0,0,1,0
1,2023-01-01,0.500763,0.048543,0.935862,0.277469,0.802465,0.614357,0.051991,0.127953,0.920881,...,0.433756,0.689518,0.908485,node_18,0.507800,0,0,0,0,1
2,2023-01-01,0.746726,0.447345,0.328318,0.869555,0.016188,0.558113,0.183280,0.078557,0.233778,...,0.902517,0.329844,0.627804,node_7,0.527733,0,0,0,1,0
3,2023-01-01,0.526692,0.870251,0.778340,0.336979,0.813050,0.789665,0.946192,0.111309,0.672244,...,0.424952,0.938086,0.360411,node_20,0.473557,0,0,0,1,0
4,2023-01-01,0.425342,0.885459,0.711212,0.458625,0.114493,0.527093,0.707678,0.754122,0.006170,...,0.609312,0.218458,0.412884,node_38,0.973990,0,0,0,0,1
5,2023-01-01,0.776035,0.978772,0.971876,0.156929,0.855481,0.611866,0.700456,0.643087,0.532672,...,0.672196,0.725376,0.616716,node_28,0.888623,0,0,1,0,0
6,2023-01-01,0.789514,0.977272,0.883109,0.605027,0.176084,0.387838,0.150732,0.495245,0.705851,...,0.204449,0.739359,0.769292,node_26,0.930801,1,0,0,0,0
7,2023-01-01,0.963772,0.429530,0.965500,0.649846,0.540162,0.240296,0.568560,0.423242,0.771131,...,0.880116,0.327576,0.231733,node_1,0.349478,0,0,0,1,0
8,2023-01-01,0.022299,0.467883,0.426562,0.517830,0.047104,0.232608,0.607945,0.259300,0.874016,...,0.638902,0.153562,0.536357,node_19,0.144293,0,0,0,1,0
9,2023-01-01,0.780019,0.778220,0.788372,0.008149,0.019734,0.488540,0.648551,0.009473,0.243506,...,0.186359,0.537288,0.683907,node_47,0.222956,0,0,0,0,1
10,2023-01-01,0.172274,0.753025,0.907197,0.339873,0.159469,0.252404,0.433671,0.721023,0.115129,...,0.164729,0.432273,0.551680,node_6,0.723050,1,0,0,0,0
11,2023-01-01,0.747688,0.803754,0.990504,0.153360,0.824241,0.173388,0.371003,0.442024,0.188972,...,0.770887,0.995303,0.227585,node_26,0.431284,0,1,0,0,0
12,2023-01-01,0.812515,0.134778,0.852174,0.611434,0.274014,0.123498,0.572512,0.420253,0.333401,...,0.699624,0.829499,0.863687,node_15,0.456033,1,0,0,0,0
13,2023-01-01,0.354114,0.992757,0.964490,0.783318,0.868177,0.379578,0.491405,0.679873,0.914650,...,0.311552,0.534288,0.319421,node_34,0.885520,0,0,0,0,1
14,2023-01-01,0.342024,0.764794,0.381099,0.487475,0.908453,0.434893,0.799599,0.245354,0.473249,...,0.820744,0.175510,0.634535,node_11,0.791817,0,0,0,1,0
15,2023-01-01,0.511985,0.280418,0.154709,0.962570,0.395526,0.805575,0.384202,0.328706,0.689203,...,0.507214,0.531120,0.912629,node_16,0.098435,1,0,0,0,0
16,2023-01-01,0.045943,0.638657,0.744851,0.428108,0.180341,0.119285,0.417214,0.644394,0.646915,...,0.967255,0.548271,0.732557,node_9,0.542264,0,1,0,0,0
17,2023-01-01,0.289359,0.422795,0.033482,0.908613,0.854269,0.166432,0.922151,0.567296,0.775966,...,0.466184,0.252084,0.339714,node_26,0.667300,1,0,0,0,0
18,2023-01-01,0.481552,0.425022,0.993224,0.588332,0.956251,0.438202,0.138701,0.484072,0.188617,...,0.339064,0.535946,0.131762,node_46,0.518894,0,0,0,0,1
19,2023-01-01,0.416678,0.758125,0.189547,0.442125,0.083836,0.248058,0.887136,0.624792,0.412836,...,0.939879,0.978179,0.394928,node_12,0.549126,0,0,1,0,0

In [23]:
#export the cleaned dataset

cleaned_data.to_csv('/Users/zxgan/FYP_Kubernetes/Dataset/cleaned_kubernetes_dataset.csv', index=False)

In [24]:
#divide the dataset by node_name

node_names = cleaned_data["node_name"].unique()
node_data = {}
for node_name in node_names:
    node_data[node_name] = cleaned_data[cleaned_data["node_name"] == node_name]

#export the divided dataset
for node_name, data in node_data.items():
    data.to_csv(f'/Users/zxgan/FYP_Kubernetes/Dataset/cleaned_dataset/node_{node_name}_dataset.csv', index=False)